services:
  postgres_v16:
    image: postgres:16-alpine
    container_name: postgres_v16
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      # Project environment variables
      TS_MONOREPO_DB_NAME: ${TS_MONOREPO_DB_NAME}
      TS_MONOREPO_DB_USER: ${TS_MONOREPO_DB_USER}
      TS_MONOREPO_DB_PASSWORD: ${TS_MONOREPO_DB_PASSWORD}
    volumes:
      - postgres_volume_v16:/var/lib/postgresql/data
      - ./initdb-v16:/docker-entrypoint-initdb.d
      - ./initdb-v16/entrypoint:/entrypoint
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env

volumes:
  postgres_volume_v16:
    name: postgres_volume_v16
